name:               ais
version:            0.1.0.0
synopsis:           ygpark blog project from stack
description:        Please see README.md
homepage:           https://github.com/ygpark2/ygpark2.github.io#readme
license:            BSD3
license-file:       LICENSE
author:             Young Gyu Park
maintainer:         ygpark2@gmail.com
copyright:          2016 Young Gyu Park.
category:           Web
# build-type:         Simple
# cabal-version:      >= 1.10

dependencies:
  - base >= 4.13.0.0 && < 5.0.0.0
  - hakyll >= 4.13.4.0 && < 5.0.0.0
  - hakyll-sass >= 0.2.4 && < 1.0.0
  - filepath >= 1.4.2.1 && < 1.5.0.0
  - process >= 1.6.9.0 && < 1.7.0.0
  - unordered-containers >= 0.2.10.0 && < 0.3.0.0
  - configurator >= 0.3.0.0 && < 0.5.0.0
  - text >= 1.2.4.0 && < 1.3.0.0
  - regex-compat >= 0.95.2.0 && < 0.96.0.0
  - regex-posix >= 0.96.0.0 && < 0.97.0.0
  - containers >= 0.6.2.1 && < 0.7.0.0
  - pandoc >= 2.9.2.1 && < 3.0.0.0
  - doctemplates >= 0.8 && < 1.0
  - time >=1.9.3 && <1.10.0
  - blaze-html == 0.9.*
  - tagsoup == 0.14.*

executables:
  site:
    main: Main.hs
    other-modules:
    - Site.Archive
    - Site.Configuration
    - Site.Context
    - Site.Language
    - Site.Meta
    - Site.Pagination
    - Site.Pandoc
    - Site.Prefixes
    - Site.Routes
    source-dirs:
    - src
    extensions: OverloadedStrings OverloadedStrings
    ghc-options:
    - -threaded
    - -Wall
    - -fwarn-tabs
    - -funbox-strict-fields
    - -O2
    - -fno-warn-unused-do-bind
  post:
    main: Post.hs
    other-modules: []
    source-dirs: src
    dependencies:
    - cmdargs >= 0.10.20 && < 0.11.0
    - filepath >= 1.4.2.1 && < 1.5.0.0
    - directory >= 1.3.6.0 && < 1.4.0.0
    - time >= 1.9.3 && < 1.10.0
    # template >= 0.2.0.10 && < 0.3.0.0
    extensions: OverloadedStrings OverloadedStrings
    ghc-options:
    - -threaded
    - -Wall
    - -fwarn-tabs
    - -funbox-strict-fields
    - -O2
    - -fno-warn-unused-do-bind