# Theme selection
# theme: default | minimal-mistakes
# themeDevelopment: default-development | minimal-mistakes

site:
  theme: default
  themeDevelopment: default-development
  url: https://ygpark2.github.io
  title: [Young Gyu's blog]
  subtitle: Thoughts, projects, and archives.
  topNavMenu:
    - title: Archive
      url: /archive/
    - title: Tags
      url: /tags/
    - title: Map
      url: /map/
    - title: Projects
      url: /projects/
    - title: About
      url: /about/
    - title: Search
      url: /pages/search/
  disqus:
    shortname: ygpark2
# Post list excerpt length (plain text)
postExcerptLengthIndex: 300
postExcerptLengthList: 300
